name = "weifengwang-traffic-orchestrator"
main = "worker.js"
compatibility_date = "2024-01-01"

# Route for custom domain
# routes = [
#   { pattern = "weifengwang.com/*", zone_name = "weifengwang.com" }
# ]

[vars]
ORIGIN_URL = "https://real-jasonwang.github.io/me"

